### ISSUE TITLE
Multiple HTML pages cannot use the same css, image

### ISSUE THREAD

**Issue by jedchang** [VladimirMikulic/parcel-plugin-custom-dist-structure#24]
There are multiple pages index.html and main.html, but the same css and image cannot be used together. Only the first one used can be displayed correctly

OS: Windows 10
Parcel version: ^1.12.4
Plugin version: ^1.1.10

package.json
```json
{
  "name": "demo-parcel",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "scripts": {
    "clean": "rm dist/index.js",
    "start": "parcel ./src/index.html ./src/main.html",
    "build": "parcel build ./src/index.html --public-url ./"
  },
  "customDistStructure": {
    "config": {
      "js": [
        ".js",
        ".js.map"
      ],
      "css": [
        ".css",
        ".css.map"
      ],
      "images": [
        ".jpg",
        ".png"
      ]
    },
    "options": {
      "development": true
    }
  },
  "dependencies": {},
  "devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/preset-env": "^7.9.6",
    "autoprefixer": "^9.7.6",
    "parcel-bundler": "^1.12.4",
    "parcel-plugin-custom-dist-structure": "^1.1.10",
    "parcel-plugin-nuke-dist": "^1.0.1",
    "postcss-modules": "^2.0.0",
    "sass": "^1.26.5"
  }
}

```

index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Empty project</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="./css/styles.css" />
  </head>
  <body>
    <div id="app">
      <div class="menu">
        <a href="./index.html" class="current">home</a>|
        <a href="./main.html">main</a>
      </div>
      <h1>home content</h1>
      <div class="pic"></div>
    </div>
    <script src="./js/index.js"></script>
  </body>
</html>
```

main.html
```html
<!DOCTYPE html>
<html>
  <head>
    <title>Empty project</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="./css/styles.css" />
  </head>
  <body>
    <div id="app">
      <div class="menu">
        <a href="./index.html">home</a>|
        <a href="./main.html" class="current">main</a>
      </div>
      <h1>main content</h1>
      <div class="pic"></div>
    </div>
    <script src="./js/index.js"></script>
  </body>
</html>
```

Preview：index.html Is normal and can be displayed

![index](https://user-images.githubusercontent.com/8979857/81780072-786f1e00-9528-11ea-9b29-e2113888253f.jpg)

Preview：main.html Is normal and can be displayed

![main](https://user-images.githubusercontent.com/8979857/81780085-7c9b3b80-9528-11ea-9d23-160ffab260dd.jpg)

But switch to main.html, it will not display properly
It seems that the css and images paths are not correct

**Comment by VladimirMikulic** [comment]
@jedchang thank you for reporting this.
I've just tested it out and you are right. In my experience, this only occurs with CSS files.
The patch should be available soon :)

**Comment by VladimirMikulic** [comment]
@jedchang v1.1.11 has been released!
It includes this fix as well as some other fixes and performance improvements.

Enjoy :rocket:

**Comment by jedchang** [comment]
Hi @VladimirMikulic 
After using version v1.1.11, an error occurs! The compiled file has no folder, only js has folder output

![10](https://user-images.githubusercontent.com/8979857/81885169-5038fb00-95cc-11ea-8ee6-875a65ff6eb6.jpg)

![11](https://user-images.githubusercontent.com/8979857/81885183-5929cc80-95cc-11ea-84db-478a7eb4452d.jpg)

**Comment by VladimirMikulic** [comment]
Hi @jedchang.
It's strange that error appears because tests are passing and I've tested it on an example project which has the same structure as yours. I've not encountered any problems.

Could you please post the error message here? Thank you.

**Comment by jedchang** [comment]
The error message is as follows

![15_x_15_08-55-51](https://user-images.githubusercontent.com/8979857/82000199-2e05b280-968a-11ea-8698-9f0d1dc4ee4f.jpg)

**Comment by VladimirMikulic** [comment]
That's odd. I've tested the plugin on Windows and there are no errors.
Is your project by any chance open source so I can clone it and see what's wrong?
If it's not, could you please set up an example repo in which plugin throws an error for you?

Thank you.

**Comment by jedchang** [comment]
Hi @VladimirMikulic ,
I put files on this repository, [test-parcel-plugin](https://github.com/jedchang/test-parcel-plugin)
Thank you

**Comment by VladimirMikulic** [comment]
@jedchang I was able to identify and fix this tricky issue.
I'll publish a new version as soon as I resolve #21. Thank you very much for reporting this critical issue and helping me identify it!

**Comment by VladimirMikulic** [comment]
Hi @jedchang. We are having a hard time resolving #21 but I didn't want you to wait until we resolve it so I've published a new version which includes this change.

Enjoy v1.1.12 & thank you for making it possible!

**Comment by jedchang** [comment]
After using the v1.1.12 version, the folder structure in dist is normal, but it still reports an error and cannot run

![err1](https://user-images.githubusercontent.com/8979857/82770382-f1e10780-9e6a-11ea-96ac-1dc5975b612b.jpg)

Error message
![err2](https://user-images.githubusercontent.com/8979857/82770388-f60d2500-9e6a-11ea-917b-563b9dcf2311.jpg)

**Comment by VladimirMikulic** [comment]
Thanks, @jedchang. I'll fix it soon.

**Comment by serhatyuna** [comment]
Hi @VladimirMikulic, thanks for your work. I am using v1.1.14 and I can say that this issue is still relevant. My config is below. Can you inform me please?

```json
"customDistStructure": {
    "config": {
      ".js": "js",
      "images": [
        ".jpg",
        ".png",
        ".svg"
      ],
      ".css": "styles",
      ".ttf": "fonts"
    },
    "options": {
      "development": true
    }
}
```

**Comment by VladimirMikulic** [comment]
Hello @serhatyuna.
I appreciate your kind words & thank you for reporting this.

Could you please provide me with an example repo that reproduces the issue?

Thank you.

**Comment by serhatyuna** [comment]
Thank you. I sent you an invitation to the project.

**Comment by VladimirMikulic** [comment]
Thank you, @serhatyuna. I'll troubleshoot the plugin and get back to you as soon as I identify the bug.

**Comment by serhatyuna** [comment]
As I upgraded to v1.1.15, `build` command runs as expected. But when the plugin is activated in development, the dependency cycle error (mentioned at [#issuecomment-628963414](https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure/issues/24#issuecomment-628963414)) still occurs. Since it still works in development without activating the plugin, there is no need to use it in development, at least in my case the problem is resolved. Actually, I wasn't expecting a fast solution. Thank you so much @VladimirMikulic. Good luck with your future work! 🥳🙌🏽

**Comment by VladimirMikulic** [comment]
Hello @serhatyuna.
Thank you for reporting the issue. Actually, it was a very a simple fix and by upgrading to v.1.1.16, you can take advantage of it.
Enjoy!
